"""
Simulated-data sanity check, requested at the meeting after reading Section 4.1
("Data generating processes") of Qu, Timmermann & Zhu (2024).

We don't need their full DGP framework (hierarchical factors, spatial AR(1), a
two-factor model) -- that's built to stress-test the *significance test itself*
under different cross-sectional dependence structures, which isn't what we're
doing. What's relevant to us is the simplest, clearest piece: their DGP 1 is
just an AR(1) process, same parameters for every series, independent across
series. This script mimics that at the panel level -- build a synthetic
country-year panel where we KNOW the true process is a shared AR(1), then run
our own pipeline on it as a sanity check. Since the data is generated by an
AR(1) by construction, AR(1) should come out clearly on top, with its ASEP
close to the true noise variance. If it doesn't, something in the pipeline is
wrong. Also the "use simulated data, check if we get similar results on a
recap" idea from the original proposal notes.

Doesn't touch the real data or results -- fully self-contained, writes to
results/simulated_dgp_check/.

Run:
    python simulated_dgp_check.py
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from src.config import RANDOM_SEED, RESULTS_DIR
from src.data import build_features
from src.metrics import asep
from src.models import ar1_predict, naive_predict, rf_predict
from src.plotting import ecdf_xy
from src.splits import split_random_rows

OUT_DIR = RESULTS_DIR / "simulated_dgp_check"
OUT_DIR.mkdir(parents=True, exist_ok=True)

N_UNITS = 100
N_YEARS = 60
N_REPLICATIONS = 200

# Same AR(1) parameters for every unit, independent across units -- the
# "clear" part of DGP 1 in Section 4.1: e_t = mu*(1-phi) + phi*e_(t-1) + eps
TRUE_MU = 2.0
TRUE_PHI = 0.6
TRUE_SIGMA = 3.0


def simulate_panel() -> pd.DataFrame:
    rng = np.random.default_rng(RANDOM_SEED)
    rows = []
    for unit in range(N_UNITS):
        y = TRUE_MU
        for t in range(N_YEARS):
            eps = rng.normal(0, TRUE_SIGMA)
            y = TRUE_MU * (1 - TRUE_PHI) + TRUE_PHI * y + eps
            rows.append({
                "unit_id": f"SIM{unit:03d}",
                "country": f"Simulated unit {unit}",
                "time": 1960 + t,
                "target": y,
            })
    return pd.DataFrame(rows)


def run_monte_carlo(panel: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for rep in range(N_REPLICATIONS):
        train_df, test_df = split_random_rows(panel, rep)
        actual = test_df["target"].to_numpy()

        rows.append({"replication": rep, "method": "naive", "asep": asep(actual, naive_predict(test_df))})
        rows.append({"replication": rep, "method": "ar1", "asep": asep(actual, ar1_predict(train_df, test_df))})
        rows.append({"replication": rep, "method": "random_forest", "asep": asep(actual, rf_predict(train_df, test_df))})

        if (rep + 1) % 50 == 0:
            print(f"Completed replication {rep + 1}/{N_REPLICATIONS}")

    return pd.DataFrame(rows)


def summarize_and_plot(asep_df: pd.DataFrame) -> None:
    asep_df.to_csv(OUT_DIR / "simulated_asep_results.csv", index=False)

    true_noise_var = TRUE_SIGMA ** 2
    summary = asep_df.groupby("method")["asep"].agg(["mean", "std"]).reset_index()
    summary["mean_minus_true_noise_var"] = summary["mean"] - true_noise_var
    summary.to_csv(OUT_DIR / "simulated_summary.csv", index=False)

    plt.figure(figsize=(7, 5))
    for method in asep_df["method"].unique():
        values, y = ecdf_xy(asep_df.loc[asep_df["method"] == method, "asep"].to_numpy())
        plt.plot(values, y, label=method)
    plt.axvline(true_noise_var, color="black", linestyle=":",
                label=f"true noise variance ({true_noise_var:.1f})")
    plt.xlabel("ASEP")
    plt.ylabel("Empirical distribution function")
    plt.title("Simulated AR(1) panel - pipeline sanity check\n(true process is a shared AR(1); AR(1) should win)")
    plt.legend()
    plt.tight_layout()
    plt.savefig(OUT_DIR / "simulated_ecdf.png", dpi=150)
    plt.close()

    print(f"\nTrue noise variance (what AR(1) should get close to): {true_noise_var:.2f}")
    print("\nAverage ASEP by method:")
    print(summary.to_string(index=False))
    print("\nSaved:")
    print(" -", OUT_DIR / "simulated_asep_results.csv")
    print(" -", OUT_DIR / "simulated_ecdf.png")
    print(" -", OUT_DIR / "simulated_summary.csv")


def main() -> None:
    print(f"Simulating a {N_UNITS}-unit, {N_YEARS}-year panel from a shared AR(1) "
          f"process (mu={TRUE_MU}, phi={TRUE_PHI}, sigma={TRUE_SIGMA})...")
    panel = simulate_panel()
    panel = build_features(panel, processed_dir=OUT_DIR)
    print(f"Simulated panel ready: {len(panel)} rows, {panel['unit_id'].nunique()} units")

    print(f"Running {N_REPLICATIONS} Monte Carlo replications on simulated data...")
    asep_df = run_monte_carlo(panel)

    summarize_and_plot(asep_df)


if __name__ == "__main__":
    main()
